cocktails/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^recipes/', include('recipes_adviser.urls',
                              namespace='recipes_adviser')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes_adviser/urls.py
from django.conf.urls import url

from . import views


app_name = 'recipes_adviser'

urlpatterns = [
    url(r'^$', views.RecipeSearchView.as_view(), name='index'),
    url(r'^ingredient/(?P<ingredient_id>[0-9]+)/$',
        views.ingredient, name='ingredient_detail'),
    url(r'^recipe/(?P<recipe_id>[0-9]+)/$', views.recipe, name='recipe_detail'),
    url(r'^tool/(?P<tool_id>[0-9]+)/$', views.tool, name='tool_detail'),
    url(r'about/$', views.about, name='about'),
    url(r'about_cocktails/$', views.about_cocktails, name='about_cocktails'),
]

templates/base.html
{% load staticfiles %}

<html lang="en">
<head>
{% block head %}
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">
  <title>{% block head_title %} Barkeeper {% endblock head_title %}</title>
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/base.css' %}">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" type="text/css">
  <link rel="stylesheet" href="//fonts.googleapis.com/css?family=Fredoka%20One" type="text/css">

  <script src="{% static 'js/jquery-1.12.3.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
{% endblock head %}
</head>

<body>
{% block body %}

  <header>
    {% block page_head %}
    <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#b-menu-1">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="nav-title navbar-brand" href="{% url 'recipes_adviser:index' %}">Barkeeper</a>
        </div>
        <div class="collapse navbar-collapse" id="b-menu-1">
          <ul class="nav navbar-nav navbar-right">
            <li class="active"><a href="{% url 'recipes_adviser:about_cocktails' %}">Виды коктейлей</a></li>
            <li><a href="{% url 'recipes_adviser:about' %}">О проекте</a></li>
          </ul>
        </div>
      </div>
    </div>
    {% endblock page_head %}
  </header>

  <div class="content container">
    <div class="row">
      {% block content %}
      {% endblock %}
    </div>
  </div>

  <footer>
    {% block footer %}
    <div class="navbar-footer navbar navbar-inverse" role="navigation">
      <div class="container">
        <div class="footer-site-info col-xs-6 col-sm-3 col-md-3 col-lg-2">Barkeeper 2016</div>
      </div>
    </div>
    {% endblock footer %}
  </footer>

{% endblock body %}
</body>
</html>